name = "kbmjj123-blog"
keep_vars = true
main = ".output/server/index.mjs"
compatibility_date = "2026-05-07"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

assets = { directory = ".output/public" }

routes = [
  { pattern = "kbmjj123.cc", zone_name = "kbmjj123.cc", custom_domain = true },
  { pattern = "www.kbmjj123.cc", zone_name = "kbmjj123.cc", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "kbmjj123-db"
database_id = "9e69c8b1-f86b-47ff-aa5d-07f53b1dfea7"

# [[kv_namespaces]]
# binding = "CACHE"
# id = ""

# [[r2_buckets]]
# binding = "CDN"
# bucket_name = "aifindr-cdn"

[vars]
API_BASE = "https://kbmjj123.cc"
# md5(kbmjj123.cc) = 273be4be4de0339309f670bee6789807
NUXT_OG_IMAGE_SECRET = "273be4be4de0339309f670bee6789807"

# [triggers]
# crons = ["0 9 * * *"]
